apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
  labels:
    app: ms-usuarios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-usuarios
  template:
    metadata:
      labels:
        app: ms-usuarios
    spec:
      containers:
      - name: ms-usuarios
        image: 871767013014.dkr.ecr.us-east-1.amazonaws.com/ms-usuarios:${IMAGE_TAG}
        ports:
        - containerPort: 8085
        env:
        - name: DB_URL
          value: "jdbc:postgresql://sanosdb-service:5432/db_usuarios"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-password

        - name: EUREKA_URL
          value: "http://eureka-service:8761/eureka/"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-service"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-service
spec:
  type: ClusterIP 
  selector:
    app: ms-usuarios
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
